export const projects = [
  {
    title: 'L. Ajwang & Associate Advocates',
    description: "The firm offers Corporate and Commercial Legal services.",
      image: '/images/L-Ajwang.png',
      tags: ['WordPress'],
      visit: 'http://lajwangadvocates.co.ke/',
      id: 0,
  },
  {
    title: 'Flyamanita',
    description: "Fly Amanita is an online mushroom products store. They sell Amanita-instilled healing remedies and natural health products.",
      image: '/images/Fly-Amanita.png',
      tags: ['WordPress'],
      visit: 'https://flyamanita.store/',
      id: 1,
  },
  {
    title: 'ISK',
    description: "The International School of Kenya is an international school offering international curriculum to students.",
      image: '/images/isk.png',
      tags: ['Google Sites'],
      visit: 'https://www.isk.ac.ke/',
      id: 2,
  },
  {
    title: 'Voomantics',
    description: "Voomantics is an innovative branding and creative marketing Studio.",
      image: '/images/Voomantics.png',
      tags: ['WordPress'],
      visit: 'https://dev.voomantics.com/',
      id: 3,
  },
  {
    title: 'KedavTech',
    description: "KedavTech is a one-stop all-under-one-roof IT tech store. They provide services such as computer sales, software development, gadget repair and also networking services.",
      image: '/images/kedav.png',
      tags: ['WordPress'],
      visit: 'https://kedavtech.co.ke/',
      id: 4,
  },
  {
    title: 'Wanamataifa Investments',
    description:"This is an Investment Arm of UNDTSACCO whose main purpose is to help members acquire property and other services at an affordable rate.",
    image: '/images/Wanamataifa-Investment.png',
    tags: ['WordPress'],
    visit: 'http://wanamataifa.co.ke/dev/',
    id: 5,
  },
  {
    title: 'SORK',
    description: "This is a website showcasing the history and services offered by the society to its members. The website is built on WordPress.",
    image: '/images/SORK.png',
    tags: ['WordPress'],
    visit: 'https://sork.or.ke/',    
    id: 6,
  },
  {
    title: 'Masta D-Signs Ltd',
    description: "This is an independent professional practice specializing in planning, design and management of architectural, landscape and interior design projects.",
      image: '/images/Masta-Design-–-Interior-Design.png',
      tags: ['WordPress'],
    visit: 'http://mastadsigns.co.ke/',
    id: 7,
  },
  {
    title: 'Engineers San Frontier\'s',
    description: "This is a website showcasing the products and services offered by an electrical engineering company. The website is built on WordPress.",
    image: '/images/san.png',
    tags: ['WordPress'],
    visit: 'https://engineerssanfrontiers.co.ke/',
    id: 8,
  },
  {
    title: 'HVAC Contractors',
    description: "This is a website showcasing the products and services offered by a company providing the highest quality HVAC systems. The website is built on CodeIgniter.",
      image: '/images/hvac.png',
      tags: ['CodeIgniter', 'MySQL'],
    visit: 'https://hvaccontractors.co.ke/public/',
    id: 9,
  },
  
];

export const TimeLineData = [
  { year: 2019, text: 'IT intern at Ministry of Labour and Social Protection.', },
  { year: 2020, text: 'Graduated from Multimedia University.', },
  { year: 2021, text: 'Trained students in Introduction to Computers and Microsoft Office Suite.', },
  { year: 2022, text: 'Content and web developing consultant at Kedavtech.', },
  { year: 2023, text: 'Freelance fullstack developer.', },
  // { year: 2021, text: 'Started my own platform', },
];