export const projects = [
  {
    title: 'Magnet Digital Marketing Agency',
    description: "Fly Amanita is an online mushroom products store. They sell Amanita-instilled healing remedies and natural health products.",
      image: '/images/Fly-Amanita.png',
      tags: ['WordPress'],
      visit: 'https://magnetdigitalmarketing.co.ke/',
      id: 0,
  },
  {
    title: 'Railsite Building and Contractors',
    description: "The firm offers Corporate and Commercial Legal services.",
      image: '/images/L-Ajwang.png',
      tags: ['WordPress'],
      visit: 'http://railsitebld.com/',
      id: 1,
  },
  {
    title: 'Indepth Research Institute (IRES)',
    description: "The International School of Kenya is an international school offering international curriculum to students.",
      image: '/images/isk.png',
      tags: ['Laravel'],
      visit: 'https://indepthresearch.org/',
      id: 2,
  },
  {
    title: 'Oplos Marketing and Media',
    description: "Voomantics is an innovative branding and creative marketing Studio.",
      image: '/images/Voomantics.png',
      tags: ['WordPress'],
      visit: 'https://oplosmarketing.co.ke/',
      id: 3,
  },
  {
    title: 'KedavTech',
    description: "KedavTech is a one-stop all-under-one-roof IT tech store. They provide services such as computer sales, software development, gadget repair and also networking services.",
      image: '/images/kedav.png',
      tags: ['WordPress'],
      visit: 'https://kedavtech.co.ke/',
      id: 4,
  },
  {
    title: 'Apollina Healthcare',
    description:"This is an Investment Arm of UNDTSACCO whose main purpose is to help members acquire property and other services at an affordable rate.",
    image: '/images/Wanamataifa-Investment.png',
    tags: ['WordPress'],
    visit: 'http://apollinahealthcare.com/',
    id: 5,
  },
  {
    title: 'Top Professionals Africa',
    description: "This is a website showcasing the history and services offered by the society to its members. The website is built on WordPress.",
    image: '/images/SORK.png',
    tags: ['WordPress'],
    visit: 'https://topprofessionals.africa/',    
    id: 6,
  },
  {
    title: 'Karington Tours & Travel',
    description: "This is an independent professional practice specializing in planning, design and management of architectural, landscape and interior design projects.",
      image: '/images/Masta-Design-–-Interior-Design.png',
      tags: ['WordPress'],
    visit: 'https://karingtontours.co.ke/',
    id: 7,
  },
  // {
  //   title: 'Engineers San Frontier\'s',
  //   description: "This is a website showcasing the products and services offered by an electrical engineering company. The website is built on WordPress.",
  //   image: '/images/san.png',
  //   tags: ['WordPress'],
  //   visit: 'https://engineerssanfrontiers.co.ke/',
  //   id: 8,
  // },
  // {
  //   title: 'HVAC Contractors',
  //   description: "This is a website showcasing the products and services offered by a company providing the highest quality HVAC systems. The website is built on CodeIgniter.",
  //     image: '/images/hvac.png',
  //     tags: ['CodeIgniter', 'MySQL'],
  //   visit: 'https://hvaccontractors.co.ke/public/',
  //   id: 9,
  // },
  
];

export const TimeLineData = [
  { year: 2019, text: 'IT intern at Ministry of Labour and Social Protection.', },
  { year: 2020, text: 'Graduated from Multimedia University.', },
  { year: 2021, text: 'Trained students in Introduction to Computers and Microsoft Office Suite.', },
  { year: 2022, text: 'Content and web developing consultant at Kedavtech.', },
  { year: 2023, text: 'Freelance fullstack developer.', },
  // { year: 2021, text: 'Started my own platform', },
];